"""Render a combined Markdown summary from one or more audit report dicts.

The summary contains statistics, class tables and file paths only — never
label content or identity text.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable, Mapping

from idocr.data.audit.report import REPORT_SUFFIX

SUMMARY_FILENAME = "dataset_summary.md"
MAX_ISSUES_LISTED = 100


def _table(headers: list[str], rows: Iterable[Iterable[Any]]) -> list[str]:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join("" if v is None else str(v) for v in row) + " |" for row in rows]
    return out + [""]


def _fmt_stats(s: Mapping[str, Any] | None, keys=("min", "median", "max")) -> str:
    return "/".join(str(s[k]) for k in keys) if s else "-"


def render_summary(reports: list[Mapping[str, Any]]) -> str:
    L: list[str] = ["# Dataset audit summary", ""]
    L += [
        "> Generated by `scripts/audit_dataset.py`. Contains statistics and file paths only — "
        "no label content or identity text. Full details: `<dataset>_report.json`.",
        "",
    ]

    # Integrity first
    L += ["## Source data integrity", ""]
    rows = []
    for r in reports:
        integ = r["sections"].get("source_integrity")
        modified = "NOT CHECKED" if integ is None else ("YES" if integ["source_data_modified"] else "NO")
        rows.append([r["dataset_name"], integ["files_checked"] if integ else "-", f"**SOURCE DATA MODIFIED: {modified}**"])
    L += _table(["Dataset", "Files hashed before/after", "Result"], rows)

    # Overview
    L += ["## Splits overview", ""]
    rows = []
    for r in reports:
        for split, s in r["sections"]["splits"].items():
            a = s.get("annotations") or {}
            apf = a.get("annotations_per_file") or {}
            rows.append([
                r["dataset_name"], split, s["images_dir"], s["labels_dir"], s["image_files"], s["label_files"],
                s["pairing"]["pairs"], len(s["pairing"]["images_without_labels"]),
                len(s["pairing"]["labels_without_images"]), len(s["images"]["corrupted"]),
                a.get("annotation_count", "-"), apf.get("mean", "-"), len(s["unexpected_files"]),
            ])
    L += _table(
        ["Dataset", "Split", "Images dir", "Labels dir", "Images", "Labels", "Pairs", "Missing labels",
         "Orphan labels", "Corrupted", "Annotations", "Ann/image (mean)", "Unexpected files"],
        rows,
    )
    for r in reports:
        rule = r["sections"].get("pairing_rule", {})
        L += [f"- **{r['dataset_name']}** pairing: {rule.get('rule')} — _{rule.get('status')}_"]
        lay = r["sections"].get("layout", {})
        L += [f"- **{r['dataset_name']}** unexpected top-level entries: {lay.get('unexpected_entries') or 'none'}"]
    L += [""]

    # Images
    L += ["## Images", ""]
    rows = []
    for r in reports:
        for split, s in r["sections"]["splits"].items():
            im = s["images"]
            rows.append([
                r["dataset_name"], split, im["count"], im["readable"], json.dumps(im["formats"]),
                json.dumps(im["channels"]), json.dumps(im["exif_orientation"]),
                _fmt_stats(im["width"]), _fmt_stats(im["height"]), im["distinct_sizes"],
                ", ".join(f"{k} ({v})" for k, v in list(im["most_common_sizes"].items())[:3]),
                _fmt_stats(im["aspect_ratio_w_over_h"]), im["unusual_sizes"]["count"],
            ])
    L += _table(
        ["Dataset", "Split", "Images", "Readable", "Formats", "Channels", "EXIF orientation",
         "Width min/med/max", "Height min/med/max", "Distinct sizes", "Top sizes", "Aspect w/h min/med/max",
         "Unusual sizes"],
        rows,
    )

    # Annotation format
    L += ["## Annotation format", ""]
    for r in reports:
        splits = r["sections"]["splits"]
        first = next((s["annotations"] for s in splits.values() if s.get("annotations")), None)
        L += [f"### {r['dataset_name']}", ""]
        if not first:
            L += ["No label inspector matched.", ""]
            continue
        L += [f"- Inspector: `{first['format']}`", f"- {first['description']}",
              f"- Transcriptions present: {first['transcriptions_present']}",
              f"- Class names: {first['class_names_note']}", ""]
        rows = [[split, json.dumps(s["annotations"]["tokens_per_line"]), json.dumps(s["annotations"]["annotation_kinds"]),
                 json.dumps(s["annotations"]["polygons"]["points_per_polygon"]),
                 json.dumps(s["annotations"]["file_format"])]
                for split, s in splits.items() if s.get("annotations")]
        L += _table(["Split", "Tokens/line", "Kinds", "Polygon points", "File format"], rows)

    # Classes
    L += ["## Classes", "",
          "Meaning column: class names are not present anywhere in the datasets. "
          "Geometry columns are medians of normalised box centre/size, given only to help a human identify classes.",
          ""]
    rows = []
    for r in reports:
        for split, s in r["sections"]["splits"].items():
            a = s.get("annotations")
            if not a:
                continue
            for cid, c in a["per_class"].items():
                g = c["geometry_normalised"]
                rows.append([
                    r["dataset_name"], split, cid, c["count"], c["files_with_class"],
                    json.dumps(c["instances_per_file"]),
                    g["cx"]["median"], g["cy"]["median"], g["w"]["median"], g["h"]["median"],
                    "Meaning not determinable from annotation files alone.",
                ])
    L += _table(["Dataset", "Split", "Class ID", "Count", "Files with class", "Instances per file {k: files}",
                 "cx", "cy", "w", "h", "Meaning"], rows)
    for r in reports:
        ids = {split: s["annotations"]["class_ids"] for split, s in r["sections"]["splits"].items() if s.get("annotations")}
        same = len({tuple(v) for v in ids.values()}) <= 1
        L += [f"- **{r['dataset_name']}** class IDs per split: {ids} — {'consistent' if same else 'INCONSISTENT'}"]
    L += [""]

    # Duplicates & leakage
    L += ["## Duplicates and split leakage", ""]
    rows = []
    for r in reports:
        d = r["sections"]["duplicates"]
        sn = r["sections"].get("source_naming", {})
        lc = d.get("label_consistency", {})
        rows.append([
            r["dataset_name"], d["exact_duplicate_groups"], d["exact_duplicate_groups_across_splits"],
            f"{lc.get('groups_with_identical_labels', '-')}/{lc.get('groups_with_conflicting_labels', '-')}",
            d["near_duplicate_pairs_across_splits"],
            f"{sn.get('images_matching_convention')}/{sn.get('images_total')}",
            sn.get("distinct_source_names"), sn.get("source_names_with_multiple_exports"),
            sn.get("max_exports_per_source"), sn.get("source_names_in_multiple_splits"),
            sn.get("images_in_cross_split_sources"), json.dumps(sn.get("cross_split_combinations")),
            f"{sn.get('dhash_median_within_same_source')} / {sn.get('dhash_median_between_sources')}",
        ])
    L += _table(["Dataset", "Exact dup groups", "Exact dup groups across splits",
                 "Dup groups: same labels / conflicting", "Near-dup pairs across splits (dHash)",
                 "Roboflow-named images", "Distinct source names", "Sources with >1 export",
                 "Max exports per source", "Sources in >1 split", "Images in cross-split sources",
                 "Cross-split combos", "dHash median within source / between sources"], rows)
    L += ["Source name = filename with the Roboflow `.rf.<hash>` suffix removed. Images sharing a source name "
          "in different splits are potential train/eval leakage; confirm visually.", ""]

    # Issues
    L += ["## Data quality issues", ""]
    for r in reports:
        counts = r["sections"].get("issue_counts", {})
        L += [f"### {r['dataset_name']}", "", f"Issue counts: {json.dumps(counts) if counts else 'none'}", ""]
        issues = r["sections"].get("issues", [])
        if issues:
            L += _table(["Split", "Path", "Line", "Problem", "Detail"],
                        ([i.get("split"), i["path"], i.get("line"), i["problem"], i.get("detail")]
                         for i in issues[:MAX_ISSUES_LISTED]))
            if len(issues) > MAX_ISSUES_LISTED:
                L += [f"_{len(issues) - MAX_ISSUES_LISTED} more in the JSON report._", ""]
    return "\n".join(L)


def write_summary(reports_dir: str | Path) -> Path:
    """Render ``dataset_summary.md`` from every ``*_report.json`` in ``reports_dir``."""
    reports_dir = Path(reports_dir)
    reports = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(reports_dir.glob(f"*{REPORT_SUFFIX}"))]
    path = reports_dir / SUMMARY_FILENAME
    path.write_text(render_summary(reports), encoding="utf-8")
    return path
